As always, let us first define a few new things we are going to study today:
<li><b>Tensorboard:</b> Is the graph visualization software included with the Tensorflow. It helps to better visualize and debug our code. </li>

The various types of tensors we can define in tensorflow are constants, placeholders and variables. We will talk about them in detail below:

Let us learn about these types while implementing. 

#### Constants

In [2]:
import tensorflow as tf
a = tf.constant(1, name='0d_const') #Creates a scalar constant
b = tf.constant([2, 3, 4], name = '1d_const') #Creates a 1d constant
c = tf.constant([1, 2, 3, 4], shape=[2,2], name='2d_const') #Creates a 2d constant 
with tf.Session() as sess:
    a_out, b_out, c_out = sess.run([a, b, c])
    print(a_out, b_out, c_out, sep='\n')

1
[2 3 4]
[[1 2]
 [3 4]]


We can also create tensors in the similar fashion as we can create arrays in numpy 

In [3]:
d = tf.zeros([2, 3], name='tensor_with_shape_2_3')
with tf.Session() as sess:
    print(sess.run(d))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


Note: If we want to print the shape or name of the tensors, we can simply do that in the following manner

In [4]:
print(d.shape)
print(d.name)

(2, 3)
tensor_with_shape_2_3:0


In [5]:
e = tf.zeros_like([1, 2, 3])
f = tf.zeros_like(d)
with tf.Session() as sess:
    print(sess.run(e))
    print(sess.run(f))

[0 0 0]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [8]:
g = tf.fill([2, 3], 5)
with tf.Session() as sess:
    print(sess.run(g))

[[5 5 5]
 [5 5 5]]


To create constant that are sequences, we can use linspace and range, similar to the numpy syntax.

In [21]:
h = tf.linspace(11.0, 17.5, 3, name="linspace0")
with tf.Session() as sess:
    print(sess.run(h))

[ 11.    14.25  17.5 ]


<i>Note: We have to provide float values as start and end to linspace. Also, it doesn't have a shape parameter. To reshape the tensor, we can do it in following manner

In [22]:
i = tf.reshape(tf.linspace(11.0, 17.0, 3, name="linspace1"), [3,1])
sess = tf.Session()
print(sess.run(i))

[[ 11.]
 [ 14.]
 [ 17.]]


In [23]:
j = tf.range(5, name='range')
print(sess.run(j))

[0 1 2 3 4]


Note: The tensors are not iterable like numpy array. Example: 

In [24]:
for i in tf.range(5):
    print(sess.run(i))

TypeError: 'Tensor' object is not iterable.

We can also create random variables similar to the numpy in tensorflow

In [26]:
j = tf.random_normal([2, 3], mean=0, stddev=2)
k = tf.truncated_normal([2, 3], mean = 0, stddev=2)
print(sess.run(j))
print(sess.run(k))

[[ 0.36369571  0.59742701  4.96911144]
 [ 1.76934052 -0.53349108  0.25750658]]
[[ 1.59691668 -1.99870002 -3.84755802]
 [-1.48355401 -1.12261379  0.05165793]]


In [29]:
l = tf.add_n([1, 2, 3, 4, 5])
print(sess.run(l))

15


#### Variables

Variables are used to store the values which may change during the execution of your algorithm (Generally, not always). Especially tensors like weights and biases, which our model learns during its execution. Following are some of the differences between Variables and constants:
<li>Constants are constant (I know this sentence seems silly, but it is important). We can assign values to variables or change during its execution</li>
<li>The value of constant is stored in the graph definition and is replicated whenever the graph is loaded. Whereas the variable's value is stored separated</li>
<li>Constant is a function where variable is a class. That's why its tf.Variable and not tf.variable. This means that Variable has methods and functions as well known as ops in tensorflow world

To see this, we can have a look at the graph definition as follows:

In [41]:
tf.reset_default_graph()
m = tf.constant([1, 2, 3, 4], name='const')
print(tf.get_default_graph().as_graph_def())

node {
  name: "const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 4
          }
        }
        tensor_content: "\001\000\000\000\002\000\000\000\003\000\000\000\004\000\000\000"
      }
    }
  }
}
versions {
  producer: 22
}



tf.Variable has several ops and we have to initialize the variables before using them. 

In [42]:
a = tf.Variable([2, 3, 4, 5], name='1dVariable')
init= tf.global_variables_initializer()
print(tf.global_variables())

[<tf.Variable '1dVariable:0' shape=(4,) dtype=int32_ref>]


tf.global_variables_initializer() with initialize all the variables. To initialise a subset or a particular variable, we can do it as follows:

In [45]:
b = tf.Variable([1, 2, 3])
c = tf.Variable([12, 3, 4])
init_ab = tf.variables_initializer([a, b], name='init_ab')
sess = tf.Session()
sess.run(init_ab)
sess.run(c.initializer)

To evaluate a variable, we have eval() ops. Also, to assign a value to a tensor we have assign() op

In [51]:
print(a.eval(session=sess))
assign_a10 = a.assign([10, 20, 30, 40])
sess.run(assign_a10)
print(a.eval(session=sess))

[2 3 4 5]
[10 20 30 40]


Similar to assign there are other function like assign_add and assign_sub 

#### Placeholders
They are used to provide the example values for traning during the execution of the tensor. It can be defined as follows 

In [56]:
n = tf.placeholder(tf.int32, shape=None)

Dtype is a required parameter for placeholders. Also, it is good practice to specify the shape of placeholders as much as possible. Generally, we specifies all the dimensions of the placeholder except the dim indicating the batch_size 

In [57]:
a = tf.placeholder(tf.int32, shape=[3])
b = tf.constant([1, 2, 3])
c = a+b
with tf.Session() as sess:
    print(sess.run(c, {a: [1, 2, 3]}))

[2 4 6]


To feed multiple batches we can do it as follows:

In [59]:
with tf.Session() as sess:
    for _ in range(4):
        print(sess.run(c, {a: [1, 2, 3]}))

[2 4 6]
[2 4 6]
[2 4 6]
[2 4 6]


We can also use dictionaries to pass values for an already assigned tensor

In [61]:
with tf.Session() as sess:
    print(sess.run(c, {a: [1, 2, 3], b: [4, 4, 4]}))

[5 6 7]
